name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.0

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3

      - name: Install Trunk
        run: wget -qO- https://github.com/thedodd/trunk/releases/download/v0.17.5/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build
        run: ./trunk build --public-url=/bevy-game-experiments
      - name: Upload binaries to artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
