name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - name: Install Trunk
        run: cargo install trunk

      - name: Build
        run: trunk build
      - name: Upload binaries to artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
